### ISSUE TITLE
timeouts when running unattended

### ISSUE THREAD

**Issue by dcsan** [wechaty/wechaty#184] opened 2017-01-04 22:34 UTC
Whenever I leave wechaty running unattended it will shortly timeout and cause the login QR code to appear.

Other things like ssh sessions are still open so it is not an issue with network connection or machine "power down".
this is on an OSX desktop mac.

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

```
1. Wechaty version: #git[4543b8f 0.6.52]
2. Darwin x64 version 16.3.0 memory 86/8192 MB
3. Docker: false
4. Node version: v6.9.1
```

### Expected behavior
Wechaty should be able to run for more than a few minutes without someone using the browser manually.

### Actual behavior
If I leave the browser open and running wechaty, 
it seems to logout after a few minutes (not sure of exact times)
The message below shows in the terminal
One time the chrome browser also became unresponsive and I had to force-quit it.
If I keep wechaty running while doing other work, it seems to run ok for an hour or more.

I'm not exactly sure how long the timeout takes to happen, I will try to track this.

```
finish readyStream()
finish readyStream()
INFO Bot error: Error: watchDogReset() watchdog reset after 60 seconds, last feed:[HEARTBEAT:[heartbeat@browser]]
INFO Bot 芝士 Cheese 奶酪 logouted
INFO Bot error: Error: watchDogReset() watchdog reset after 180 seconds, last feed:[HEARTBEAT:[onBrowserDead() set a timeout of 180 seconds to prevent unknown state change]]
```

### Steps to reproduce the behavior (and fixes, if any)
run a wechaty bot, 
scan to login
leave your machine unattended.
wechaty will stop working soon.
you will get logged out message in terminal
browser appears to be frozen sometimes, in other times it will be showing the "login" QRCode again.

### Paste the full output logs here with `WECHATY_LOG=silly` set

note this maybe affected by the WiFi network we have here, occasionally dropping out.
I see these errors below also
However, wechaty seems to be able to reconnect after these and function again.

```
finish readyStream()
WARN PuppetWebBrowser execute() exception: EPIPE write EPIPE, Error: EPIPE write EPIPE
    at ClientRequest.<anonymous> (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:345:10)
    at onwrite (_stream_writable.js:363:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:468:13)
WARN PuppetWebBridge execute() exception: EPIPE write EPIPE
WARN PuppetWebBridge proxyWechaty() noWechaty exception: Error: EPIPE write EPIPE
    at ClientRequest.<anonymous> (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:345:10)
    at onwrite (_stream_writable.js:363:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:468:13)
```

here's another version of the error
```
  bot:RoomData no data for oneRoom 杭州兼职 +0ms
INFO Bot error: Error: watchDogReset() watchdog reset after 60 seconds, last feed:[HEARTBEAT:[heartbeat@browser]]
INFO Bot 芝士 Cheese 奶酪 logouted
INFO Bot error: Error: watchDogReset() watchdog reset after 180 seconds, last feed:[HEARTBEAT:[onBrowserDead() set a timeout of 180 seconds to prevent unknown state change]]
WARN PuppetWebBrowser execute() exception: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -, TimeoutError: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -600.005
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.2 x86_64)
    at WebDriverError (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/error.js:27:5)
    at TimeoutError (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/error.js:238:5)
    at Object.checkLegacyResponse (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
WARN PuppetWebBridge execute() exception: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -600.005
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.2 x86_64)
WARN PuppetWebBridge proxyWechaty() noWechaty exception: TimeoutError: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -600.005
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.2 x86_64)
    at WebDriverError (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/error.js:27:5)
    at TimeoutError (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/error.js:238:5)
    at Object.checkLegacyResponse (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
WARN MediaMessage ready() exception: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -600.005
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.2 x86_64)
ERR PuppetWebEvent onServerMessage() exception: TimeoutError: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -600.005
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.2 x86_64)
    at WebDriverError (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/error.js:27:5)
    at TimeoutError (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/error.js:238:5)
    at Object.checkLegacyResponse (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/dc/dev/rikai/wechaty/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
(node:33770) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): TimeoutError: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -600.005
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.2 x86_64)
                                                              
```

**Comment by zixia** [comment] 2017-01-05 12:46
It's strange, because according to my experience, I had never met this issue.

@dcsan Could you please provide a shortest bot script code posted here, so I can try it on my mac?

@lijiarui Had you had some issue like this before?

**Comment by lijiarui** [comment] 2017-01-06 02:29
I had the issue like this sometimes,  I'm trying to find the reason...

**Comment by dcsan** [comment] 2017-01-08 18:25
OK when i have some time I'll try to create a more minimal bot script (although existing one is quite minimal already). And it is hard to reproduce as I need to leave a mac running it for ~ some time.

**Comment by zixia** [comment] 2017-01-09 08:33
@dcsan That would be great to **be able to reproduce** your issue on another machine.

Yesterday @lijiarui reproduced her issue. After inspecting the system, we found that it's because of the Shadowsocks.

@lijiarui run shadowsocks in the **global** mode, which will cause TCP socket can not connect to localhost(127.0.0.1). However, Wechaty needs to IPC with itself by listening on localhost. 

After quit shadowsocks, this issue was gone.

I do not know whether your issue has the same reason, just FYI.

**Comment by zixia** [comment] 2017-02-10 08:14
@dcsan Hope you are doing well those days with the code! 

I'll close this issue for now, if you still experiencing any problems, please feel free to open a new issue.

**Closed by zixia** 2017-02-10 08:14 UTC

**Comment by dcsan** [comment] 2017-02-10 10:41
Thanks for the tip on shadowsocks. i'm not running SS locally but our local network is running some type of VPN. I'll try in some other environments
