### ISSUE TITLE
PuppetPad Keep logging in and out

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty#1488] opened 2018-07-17 13:59 UTC
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China) Canada
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using? Home Internet -- Bell

I don't have the details now, but keep this as a placeholder for the problem that people have been seeing. 

The old log that I had:

When it happens, it seems that the communication with sever is extremely difficult. For e.g., the `syncContactsAndRooms` request should be sent right after login, but it'll take ***5 minutes*** after login to fail:

```
22:20:03 INFO Wechaty start() v0.17.117 is starting...
22:20:03 INFO Wechaty initPuppet() using puppet: padchat
Contact<me> login
22:25:36 WARN PuppetPadchatManager syncContactsAndRooms() cannot get array result: {"message":"不支持的请求","status":-19}
```

Moreover, after such warning, no WX message can be received, and after 2 hours (20:19 ~ 22:19), it error out:

```
20:19:13 WARN PuppetPadchatManager syncContactsAndRooms() cannot get array result: {"message":"不支持的请求","status":-19}
22:19:02 WARN PadchatRpc initWebSocket() ws.on(close) 1006
22:19:02 WARN PuppetPadchat startManager() manager.on(reset) for ws.on(close, 1006. Restarting PuppetPadchat ... 
Contact<me> logout
22:19:02 WARN PuppetPadchatManager startCheckScan() checkScanLoop() exception: Error: WebSocket is not open: readyState 3 (CLOSED)
22:19:02 WARN PuppetPadchat startManager() manager.on(reset) for startCheckScan() checkScanLoop() exception. Restarting PuppetPadchat ... 
22:19:02 WARN PadchatRpc initWebSocket() ws.on(error) Error: connect ECONNREFUSED 54.223.73.175:8788
Error: Error: connect ECONNREFUSED 54.223.73.175:8788
```

Lots of WX messages should have been logged to the console during this period. 

Such logging in and out went on and on until I broke it out in the morning, after the whole night not getting any normal wx message logged.

**To duplicate:**

I was just using the vanilla https://github.com/Chatie/wechaty-getting-started/blob/master/examples/starter-bot.js with PuppetPadchat.

**Comment by zixia** [comment] 2018-07-18 02:16
It will be easy to debug if you could enable `WECHATY_LOG=silly` for your program for detailed log messages.

**Comment by suntong** [comment] 2018-07-18 23:47
Yeah, I know, that's why I said, _"I don't have the details now, but keep this as a placeholder"_. 

I'll have a new phone in a week or so, then I can give it another go.

**Comment by zixia** [comment] 2018-08-19 04:29
@suntong Hello, can you reproduce it with the latest version of  wechaty@0.20 and wechaty-puppet-padchat@0.14?

**Comment by suntong** [comment] 2018-08-27 03:57
I was about to give it a try when I saw a flurry of reports claiming that the latest code is still having the same problem. So I think I'd better defer to their detailed bug report instead.

**Comment by huan** [comment] 2021-03-22 03:50
Close this issue because the padchat has been deprecated already.

**Closed by huan** 2021-03-22 03:50 UTC
